


class TrendingProduct {
  static Map<String, dynamic> trendingProduct = {
    "products": [
      {
        "productId": 14,
        "category_id": 8,
        "sub_category_id": 10,
        "child_category_id": 11,
        "name_en": "OnePlus Nord N30 SE",
        "image": "images/product/240523-Z5SEJQ.png",
        "reg_price": 15999,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 15,
        "category_id": 8,
        "sub_category_id": 10,
        "child_category_id": 11,
        "name_en": "Xiaomi Redmi Note 13",
        "image": "images/product/240523-EHMWRV.png",
        "reg_price": 22999,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 16,
        "category_id": 8,
        "sub_category_id": 10,
        "child_category_id": 12,
        "name_en": "Samsung Tab A8",
        "image": "images/product/240523-KZJRBN.png",
        "reg_price": 24999,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 17,
        "category_id": 8,
        "sub_category_id": 10,
        "child_category_id": 12,
        "name_en": "Apple iPad 1th gen",
        "image": "images/product/240523-KT9OCT.png",
        "reg_price": 50000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 18,
        "category_id": 8,
        "sub_category_id": 13,
        "child_category_id": 15,
        "name_en": "Hp Pavilion 13.3 FHD",
        "image": "images/product/240523-A2OFYT.png",
        "reg_price": 73000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 19,
        "category_id": 8,
        "sub_category_id": 13,
        "child_category_id": 15,
        "name_en": "Macbook Air",
        "image": "images/product/240523-PMXZVT.png",
        "reg_price": 390000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 20,
        "category_id": 8,
        "sub_category_id": 13,
        "child_category_id": 14,
        "name_en": "Lenovo IdeaCentre",
        "image": "images/product/240523-9PT6MI.png",
        "reg_price": 75000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 21,
        "category_id": 8,
        "sub_category_id": 13,
        "child_category_id": 14,
        "name_en": "HP AIO ProOne 240 G9 12th Gen",
        "image": "images/product/240523-VLVKBS.png",
        "reg_price": 80000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 22,
        "category_id": 9,
        "sub_category_id": 16,
        "child_category_id": 20,
        "name_en": "Blue Casual Shirt",
        "image": "images/product/240523-YARUKV.png",
        "reg_price": 1000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 23,
        "category_id": 9,
        "sub_category_id": 16,
        "child_category_id": 20,
        "name_en": "Polo t-shirt",
        "image": "images/product/240523-WEPZSJ.png",
        "reg_price": 1500,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 24,
        "category_id": 9,
        "sub_category_id": 16,
        "child_category_id": 21,
        "name_en": "Jeans",
        "image": "images/product/240523-HNM7L8.png",
        "reg_price": 1300,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 25,
        "category_id": 9,
        "sub_category_id": 16,
        "child_category_id": 21,
        "name_en": "Gabardine",
        "image": "images/product/240523-F6AZOH.png",
        "reg_price": 1600,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 26,
        "category_id": 9,
        "sub_category_id": 17,
        "child_category_id": 18,
        "name_en": "Red Gown",
        "image": "images/product/240523-AVUKOM.png",
        "reg_price": 20000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 27,
        "category_id": 9,
        "sub_category_id": 17,
        "child_category_id": 18,
        "name_en": "Green Gown",
        "image": "images/product/240523-FGMHEP.png",
        "reg_price": 23000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 28,
        "category_id": 9,
        "sub_category_id": 17,
        "child_category_id": 19,
        "name_en": "Jamdani 3 Piece",
        "image": "images/product/240523-3FMCQT.png",
        "reg_price": 22000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      },
      {
        "productId": 29,
        "category_id": 9,
        "sub_category_id": 17,
        "child_category_id": 19,
        "name_en": "Katan 3 Piece Update",
        "image": "images/product/240523-LSGSTT.png",
        "reg_price": 23000,
        "dis_type": 0,
        "dis_price": 0,
        "brand": "Nokia",
        "stock": "100",
        "rating": 0
      }
    ]
  };
}
